# Generated by Django 5.0.7 on 2024-07-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_verifed',
            new_name='is_verified',
        ),
    ]
