# Generated by Django 5.0.7 on 2024-10-15 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arpan', '0005_remove_addcomment_post_remove_blog_blog_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programming_laguage', models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('Vanila Javascript', 'Vanila Javascript'), ('Node Js', 'Node Js'), ('WordPress', 'WordPress'), ('Laravel', 'Laravel')], max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=250)),
                ('project_type', models.CharField(choices=[('Clients', 'Clients'), ('Personal', 'Personal')], max_length=200)),
                ('project_staus', models.CharField(choices=[('Complete', 'Complete'), ('Working', 'Working')], max_length=200)),
                ('main_image', models.ImageField(upload_to='Project Image')),
                ('project_heading', models.CharField(max_length=50)),
                ('project_short_dec', models.CharField(max_length=255)),
                ('project_keypoint1', models.CharField(max_length=50)),
                ('project_keypoint2', models.CharField(max_length=50)),
                ('project_keypoint3', models.CharField(max_length=50)),
                ('project_keypoint4', models.CharField(max_length=50)),
                ('related_image1', models.ImageField(upload_to='Project Image')),
                ('related_image2', models.ImageField(upload_to='Project Image')),
                ('related_image3', models.ImageField(upload_to='Project Image')),
                ('scrollable_image', models.ImageField(upload_to='Project Image')),
                ('text_for_scrollable_img', models.CharField(max_length=255)),
                ('conclusion_img', models.ImageField(upload_to='Project Image')),
                ('conclusion_txt', models.CharField(max_length=255)),
                ('conclusion_keypoint1', models.TextField(max_length=50)),
                ('conclusion_keypoint2', models.TextField(max_length=50)),
                ('conclusion_keypoint3', models.TextField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('project_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_category', to='arpan.projectcategory')),
            ],
        ),
    ]
