# Generated by Django 5.0.7 on 2024-10-15 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arpan', '0006_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
