# Generated by Django 5.0.7 on 2024-10-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arpan', '0007_rename_projects_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='conclusion_keypoint1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='conclusion_keypoint2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='conclusion_keypoint3',
            field=models.CharField(max_length=50),
        ),
    ]
